using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TestvaerkstedetToolkit.Models
{
    /// <summary>
    /// Primary Key information med sammensatte PK support
    /// </summary>
    public class PrimaryKeyInfo
    {
        /// <summary>
        /// Liste af valgte eksisterende kolonne navne til PK
        /// </summary>
        public List<string> ExistingColumnNames { get; set; } = new List<string>();

        /// <summary>
        /// Om der skal tilføjes en auto-genereret kolonne til PK
        /// </summary>
        public bool IncludeAutoGenerated { get; set; }

        /// <summary>
        /// Navn på auto-genereret kolonne (standard: "AutoID")
        /// </summary>
        public string AutoGeneratedColumnName { get; set; } = "AutoID";

        /// <summary>
        /// Computed property: Er det en sammensatte PK?
        /// </summary>
        public bool IsComposite => GetAllPrimaryKeyColumns().Count > 1;

        /// <summary>
        /// Computed property: Har den kun auto-generated?
        /// </summary>
        public bool IsOnlyAutoGenerated => ExistingColumnNames.Count == 0 && IncludeAutoGenerated;

        /// <summary>
        /// Computed property: Har den kun eksisterende kolonner?
        /// </summary>
        public bool IsOnlyExisting => ExistingColumnNames.Count > 0 && !IncludeAutoGenerated;

        /// <summary>
        /// Hent alle PK-kolonner i rækkefølge: eksisterende først, auto-generated sidst
        /// </summary>
        public List<string> GetAllPrimaryKeyColumns()
        {
            var result = new List<string>(ExistingColumnNames);
            if (IncludeAutoGenerated)
            {
                result.Add(AutoGeneratedColumnName);
            }
            return result;
        }

        /// <summary>
        /// Generer PK navn til tableIndex.xml
        /// </summary>
        public string GeneratePrimaryKeyName(string tableName)
        {
            var pkColumns = GetAllPrimaryKeyColumns();
            if (pkColumns.Count == 0)
                return $"PK_{tableName}";

            return $"PK_{tableName}_{string.Join("_", pkColumns)}";
        }

        /// <summary>
        /// Validering: Mindst én PK-komponent skal være defineret
        /// </summary>
        public bool IsValid()
        {
            return ExistingColumnNames.Count > 0 || IncludeAutoGenerated;
        }

        /// <summary>
        /// Beregn hvor mange ekstra kolonner der skal tilføjes til hver split
        /// </summary>
        public int GetAdditionalColumnsPerSplit()
        {
            // Eksisterende kolonner duplikeres, auto-generated tilføjes
            return ExistingColumnNames.Count + (IncludeAutoGenerated ? 1 : 0);
        }
    }
}