using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TestvaerkstedetToolkit.Models
{
    /// <summary>
    /// UIDataContainer med TableIndex metadata og composite PK support
    /// </summary>
    public class UIDataContainer
    {
        public string XMLPath { get; set; }
        public string XSDPath { get; set; }
        public string TableIndexPath { get; set; }
        public TableIndexEntry OriginalTableEntry { get; set; }    // KOMPLET TableIndex metadata
        public string OriginalTableName => OriginalTableEntry?.Name ?? "";
        public string OriginalNamespace { get; set; }
        public int TotalRows { get; set; }

        /// <summary>
        /// Primary Key konfiguration med composite support
        /// </summary>
        public PrimaryKeyInfo PrimaryKey { get; set; } = new PrimaryKeyInfo();

        // BACKWARD COMPATIBILITY PROPERTIES - deprecated men bevaret til eksisterende kode
        [Obsolete("Brug PrimaryKey.GetAllPrimaryKeyColumns()[0] i stedet")]
        public string PrimaryKeyName
        {
            get
            {
                var pkColumns = PrimaryKey?.GetAllPrimaryKeyColumns();
                return pkColumns?.FirstOrDefault() ?? "";
            }
            set
            {
                // Migration support: hvis der sættes en enkelt PK via denne property
                if (PrimaryKey == null) PrimaryKey = new PrimaryKeyInfo();
                PrimaryKey.ExistingColumnNames.Clear();
                if (!string.IsNullOrEmpty(value))
                {
                    PrimaryKey.ExistingColumnNames.Add(value);
                }
            }
        }

        [Obsolete("Brug PrimaryKey.IncludeAutoGenerated i stedet")]
        public bool UseNewPrimaryKey
        {
            get => PrimaryKey?.IncludeAutoGenerated == true && PrimaryKey?.ExistingColumnNames.Count == 0;
            set
            {
                if (PrimaryKey == null) PrimaryKey = new PrimaryKeyInfo();
                PrimaryKey.IncludeAutoGenerated = value;
                if (value)
                {
                    // Hvis UseNewPrimaryKey=true, clear eksisterende kolonner (old behavior)
                    PrimaryKey.ExistingColumnNames.Clear();
                }
            }
        }

        public List<SplitTable> Tables { get; set; } = new List<SplitTable>();
        public List<XMLColumn> AllColumns { get; set; } = new List<XMLColumn>();
        public string IntegrityDescription { get; set; }
        public Dictionary<string, string> TableDescriptions { get; set; } = new Dictionary<string, string>();

        /// <summary>
        /// Validate at alle split tabeller har korrekt metadata og PK konfiguration
        /// </summary>
        public bool ValidateSplitConfiguration()
        {
            if (OriginalTableEntry == null || Tables.Count == 0)
                return false;

            // Validér PK konfiguration
            if (PrimaryKey == null || !PrimaryKey.IsValid())
                return false;

            // Tjek at første split er markeret korrekt
            if (Tables.Count(t => t.IsFirstSplit) != 1)
                return false;

            // Tjek at alle kolonner er tilstede
            var totalSplitColumns = Tables.SelectMany(t => t.Columns).Count();
            var originalColumns = OriginalTableEntry.Columns.Count;

            return totalSplitColumns <= originalColumns; // Kan være mindre pga. PK overlap
        }

        /// <summary>
        /// Beregn tilgængelig kapacitet per split efter PK-kolonner
        /// </summary>
        public int GetAvailableDataColumnsPerSplit()
        {
            int pkColumns = PrimaryKey?.GetAdditionalColumnsPerSplit() ?? 0;
            return Math.Max(0, 950 - pkColumns);
        }

        /// <summary>
        /// Hent det primære PK-navn til backward compatibility
        /// </summary>
        public string GetPrimaryKeyDisplayName()
        {
            if (PrimaryKey == null) return "";

            var pkColumns = PrimaryKey.GetAllPrimaryKeyColumns();
            if (pkColumns.Count == 0) return "";
            if (pkColumns.Count == 1) return pkColumns[0];

            return $"Composite: {string.Join(", ", pkColumns)}";
        }
    }
}