using System.Linq;
using TestvaerkstedetToolkit.Models;

namespace TestvaerkstedetToolkit.Services
{
    /// <summary>
    /// Centraliseret AutoID management - single point of truth
    /// </summary>
    public static class AutoIDManager
    {
        /// <summary>
        /// Sikrer AutoID eksisterer i AllColumns hvis PK konfiguration kræver det
        /// DETTE er det ENESTE sted AutoID må oprettes!
        /// </summary>
        public static void EnsureAutoIDInAllColumns(UIDataContainer uiData)
        {
            var pkInfo = uiData.PrimaryKey;
            if (pkInfo == null || !pkInfo.IncludeAutoGenerated)
                return;

            // Tjek om AutoID allerede eksisterer
            if (uiData.AllColumns.Any(c => c.Name == pkInfo.AutoGeneratedColumnName))
            {
                System.Diagnostics.Debug.WriteLine($"AutoID '{pkInfo.AutoGeneratedColumnName}' allerede i AllColumns - springer over");
                return;
            }

            // Opret AutoID kolonne
            var autoIDColumn = new XMLColumn
            {
                Name = pkInfo.AutoGeneratedColumnName,
                ColumnID = $"c{uiData.AllColumns.Count + 1}",
                DataType = "INTEGER",
                TypeOriginal = "",
                IsNullable = false,
                Description = "Auto-genereret primærnøgle til split tabel kobling",
                Position = uiData.AllColumns.Count + 1
            };

            uiData.AllColumns.Add(autoIDColumn);
            System.Diagnostics.Debug.WriteLine($"AutoID '{pkInfo.AutoGeneratedColumnName}' tilføjet til AllColumns på position {autoIDColumn.Position}");
        }
    }
}