using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Windows.Forms;
using TestvaerkstedetToolkit.Models;

namespace TestvaerkstedetToolkit.Controls
{
    /// <summary>
    /// User Control til composite primary key selektion - OPTIMIZED VERSION
    /// </summary>
    public partial class CompositePKSelector : UserControl
    {
        private CheckedListBox clbExistingColumns;
        private CheckBox chkIncludeAutoGenerated;
        private TextBox txtAutoGeneratedName;
        private Label lblExistingColumns;
        private Label lblPreview;
        private Label lblCapacityInfo;
        private Label lblPreviewValue;
        private Label lblCapacityValue;

        private TableIndexEntry _currentTableEntry;
        private PrimaryKeyInfo _primaryKeyInfo;

        public event EventHandler PrimaryKeyChanged;

        public CompositePKSelector()
        {
            InitializeComponent();
            _primaryKeyInfo = new PrimaryKeyInfo();
        }

        /// <summary>
        /// Hent aktuel PK konfiguration
        /// </summary>
        public PrimaryKeyInfo GetPrimaryKeyInfo()
        {
            return _primaryKeyInfo;
        }

        /// <summary>
        /// Sæt PK konfiguration (til loading af eksisterende)
        /// </summary>
        public void SetPrimaryKeyInfo(PrimaryKeyInfo pkInfo)
        {
            if (pkInfo == null) return;

            _primaryKeyInfo = pkInfo;
            UpdateUIFromPrimaryKeyInfo();
        }

        /// <summary>
        /// Load tabel data og opdater UI
        /// </summary>
        public void LoadTableData(TableIndexEntry tableEntry)
        {
            _currentTableEntry = tableEntry;
            PopulateExistingColumns();
            UpdatePreview();
        }

        private void InitializeComponent()
        {
            this.SuspendLayout();

            // Setup main container - expanded to use full allocated space
            this.Size = new Size(720, 320);
            this.BackColor = SystemColors.Control;

            // Existing columns label
            lblExistingColumns = new Label
            {
                Text = "Vælg eksisterende kolonner til primærnøgle:",
                Location = new Point(10, 10),
                Size = new Size(700, 25),
                Font = new Font("Microsoft Sans Serif", 9F, FontStyle.Bold)
            };
            this.Controls.Add(lblExistingColumns);

            // Existing columns checkedlistbox - much larger for better overview
            clbExistingColumns = new CheckedListBox
            {
                Location = new Point(10, 35),
                Size = new Size(450, 120),  // Larger for better column visibility
                CheckOnClick = true,
                SelectionMode = SelectionMode.One,
                IntegralHeight = false,
                Font = new Font("Courier New", 8.25F)
            };
            clbExistingColumns.ItemCheck += ClbExistingColumns_ItemCheck;
            this.Controls.Add(clbExistingColumns);

            // Auto-generated checkbox - positioned to the right
            chkIncludeAutoGenerated = new CheckBox
            {
                Text = "Tilføj auto-genereret kolonne\ntil primærnøgle",
                Location = new Point(480, 35),
                Size = new Size(230, 50),
                Font = new Font("Microsoft Sans Serif", 9F, FontStyle.Bold)
            };
            chkIncludeAutoGenerated.CheckedChanged += ChkIncludeAutoGenerated_CheckedChanged;
            this.Controls.Add(chkIncludeAutoGenerated);

            // Auto-generated name textbox - positioned under checkbox
            txtAutoGeneratedName = new TextBox
            {
                Text = "AutoID",
                Location = new Point(480, 95),
                Size = new Size(150, 23),
                Enabled = false
            };
            txtAutoGeneratedName.TextChanged += TxtAutoGeneratedName_TextChanged;
            this.Controls.Add(txtAutoGeneratedName);

            // Preview section - moved down with more space
            lblPreview = new Label
            {
                Text = "Primærnøgle preview:",
                Location = new Point(10, 170),
                Size = new Size(150, 20),
                Font = new Font("Microsoft Sans Serif", 9F, FontStyle.Bold)
            };
            this.Controls.Add(lblPreview);

            // Preview value - larger area
            lblPreviewValue = new Label
            {
                Text = "Ingen primærnøgle valgt",
                Location = new Point(170, 170),
                Size = new Size(540, 35),
                ForeColor = Color.DarkRed,
                Font = new Font("Microsoft Sans Serif", 9F, FontStyle.Regular)
            };
            this.Controls.Add(lblPreviewValue);

            // Capacity info label
            lblCapacityInfo = new Label
            {
                Text = "Tilgængelig plads per split:",
                Location = new Point(10, 200),
                AutoSize = true,
                Font = new Font("Microsoft Sans Serif", 9F, FontStyle.Bold)
            };
            this.Controls.Add(lblCapacityInfo);

            // Capacity value - much larger area for comprehensive text
            lblCapacityValue = new Label
            {
                Text = "Vælg primærnøgle for beregning",
                Location = new Point(280, 200), // Flyttet fra 250 til 280
                Size = new Size(430, 80),       // Reduceret bredde tilsvarende (540 → 430)
                ForeColor = Color.DarkGreen,
                Font = new Font("Microsoft Sans Serif", 9F, FontStyle.Regular)
            };
            this.Controls.Add(lblCapacityValue);

            // Info text at bottom - new addition for better user guidance
            Label lblInfo = new Label
            {
                Text = "💡 Sammensat primærnøgle: Vælg flere kolonner for øget unikhed",
                Location = new Point(10, 290),
                Size = new Size(700, 20),
                ForeColor = Color.DarkBlue,
                Font = new Font("Microsoft Sans Serif", 8.25F, FontStyle.Italic)
            };
            this.Controls.Add(lblInfo);

            this.ResumeLayout(false);
        }

        private void PopulateExistingColumns()
        {
            clbExistingColumns.Items.Clear();

            if (_currentTableEntry?.Columns == null) return;

            foreach (var column in _currentTableEntry.Columns.OrderBy(c => c.Position))
            {
                string nullableText = column.IsNullable ? "nullable" : "not null";
                string displayText = $"{column.ColumnID}: {column.Name} ({column.DataType}, {nullableText})";

                clbExistingColumns.Items.Add(displayText);
            }

            // Auto-select eksisterende PK hvis tilgængelig
            if (!string.IsNullOrEmpty(_currentTableEntry.PrimaryKeyName))
            {
                for (int i = 0; i < clbExistingColumns.Items.Count; i++)
                {
                    string itemText = clbExistingColumns.Items[i].ToString();
                    if (itemText.Contains($": {_currentTableEntry.PrimaryKeyName} ("))
                    {
                        clbExistingColumns.SetItemChecked(i, true);
                        System.Diagnostics.Debug.WriteLine($"Auto-selected PK: {_currentTableEntry.PrimaryKeyName}");
                        break;
                    }
                }
            }
        }

        private void ClbExistingColumns_ItemCheck(object sender, ItemCheckEventArgs e)
        {
            // Update efter UI event er færdig (async pattern)
            this.BeginInvoke(new Action(() =>
            {
                UpdatePrimaryKeyInfoFromUI();
                UpdatePreview();
                PrimaryKeyChanged?.Invoke(this, EventArgs.Empty);
            }));
        }

        private void ChkIncludeAutoGenerated_CheckedChanged(object sender, EventArgs e)
        {
            txtAutoGeneratedName.Enabled = chkIncludeAutoGenerated.Checked;

            if (!chkIncludeAutoGenerated.Checked)
            {
                txtAutoGeneratedName.Text = "AutoID"; // Reset to default
            }

            UpdatePrimaryKeyInfoFromUI();
            UpdatePreview();
            PrimaryKeyChanged?.Invoke(this, EventArgs.Empty);
        }

        private void TxtAutoGeneratedName_TextChanged(object sender, EventArgs e)
        {
            UpdatePrimaryKeyInfoFromUI();
            UpdatePreview();
            PrimaryKeyChanged?.Invoke(this, EventArgs.Empty);
        }

        private void UpdatePrimaryKeyInfoFromUI()
        {
            _primaryKeyInfo.ExistingColumnNames.Clear();
            _primaryKeyInfo.IncludeAutoGenerated = chkIncludeAutoGenerated.Checked;
            _primaryKeyInfo.AutoGeneratedColumnName = txtAutoGeneratedName.Text?.Trim() ?? "AutoID";

            for (int i = 0; i < clbExistingColumns.Items.Count; i++)
            {
                if (clbExistingColumns.GetItemChecked(i))
                {
                    string itemText = clbExistingColumns.Items[i].ToString();
                    string columnName = ExtractColumnNameFromDisplayText(itemText);
                    _primaryKeyInfo.ExistingColumnNames.Add(columnName);
                }
            }
        }

        private string ExtractColumnNameFromDisplayText(string displayText)
        {
            // "c1: barn_id (VARCHAR, not null)" → "barn_id"
            int colonIndex = displayText.IndexOf(": ");
            int parenIndex = displayText.IndexOf(" (");

            if (colonIndex > 0 && parenIndex > colonIndex)
            {
                return displayText.Substring(colonIndex + 2, parenIndex - colonIndex - 2).Trim();
            }

            return displayText;
        }

        /// <summary>
        /// UpdateUIFromPrimaryKeyInfo med korrekt kolonne matching
        /// </summary>
        private void UpdateUIFromPrimaryKeyInfo()
        {
            // Update existing columns checkboxes med korrekt matching
            for (int i = 0; i < clbExistingColumns.Items.Count; i++)
            {
                string itemText = clbExistingColumns.Items[i].ToString();
                string columnName = ExtractColumnNameFromDisplayText(itemText);  // Use samme metode!

                bool shouldBeChecked = _primaryKeyInfo.ExistingColumnNames.Contains(columnName);
                clbExistingColumns.SetItemChecked(i, shouldBeChecked);
            }

            // Update auto-generated controls
            chkIncludeAutoGenerated.Checked = _primaryKeyInfo.IncludeAutoGenerated;
            txtAutoGeneratedName.Text = _primaryKeyInfo.AutoGeneratedColumnName;
            txtAutoGeneratedName.Enabled = _primaryKeyInfo.IncludeAutoGenerated;

            UpdatePreview();
        }

        private void UpdatePreview()
        {
            var pkColumns = _primaryKeyInfo.GetAllPrimaryKeyColumns();

            if (pkColumns.Count == 0)
            {
                lblPreviewValue.Text = "Ingen primærnøgle valgt - konfigurer først";
                lblPreviewValue.ForeColor = Color.DarkRed;

                lblCapacityValue.Text = "Maks 1000 kolonner per split tabel er tilladt. " +
                                       "Vælg primærnøgler for at se tilgængelig kapacitet til data-kolonner.";
                lblCapacityValue.ForeColor = Color.Gray;
                return;
            }

            // Beregn kapacitet med detaljeret forklaring
            int totalPKColumns = pkColumns.Count;
            int availableDataColumns = Math.Max(0, 950 - totalPKColumns);

            // Update preview baseret på PK type
            if (pkColumns.Count == 1)
            {
                lblPreviewValue.Text = $"Enkelt primærnøgle: {pkColumns[0]}";
                lblPreviewValue.ForeColor = Color.DarkGreen;

                lblCapacityValue.Text = $"Split kapacitet: {availableDataColumns} data-kolonner per tabel. " +
                                       $"Primærnøglen ({pkColumns[0]}) duplikeres til alle split tabeller, " +
                                       $"så {availableDataColumns} kolonner tilbage til data. " +
                                       $"Beregning: 950 - 1 PK = {availableDataColumns} data-kolonner.";
                lblCapacityValue.ForeColor = Color.DarkGreen;
            }
            else
            {
                lblPreviewValue.Text = $"Sammensat primærnøgle: {string.Join(", ", pkColumns)}";
                lblPreviewValue.ForeColor = Color.DarkBlue;

                lblCapacityValue.Text = $"Split kapacitet: {availableDataColumns} data-kolonner per tabel. " +
                                       $"Alle {totalPKColumns} primærnøgle komponenter duplikeres til hver split tabel. " +
                                       $"Beregning: 950 - {totalPKColumns} PK komponenter = {availableDataColumns} data-kolonner.";

                // Farve baseret på tilgængelig kapacitet
                if (availableDataColumns > 800)
                    lblCapacityValue.ForeColor = Color.DarkBlue;
                else if (availableDataColumns > 500)
                    lblCapacityValue.ForeColor = Color.Orange;
                else
                    lblCapacityValue.ForeColor = Color.DarkRed;
            }

            // Advarsel hvis for mange PK komponenter
            if (availableDataColumns < 100)
            {
                lblCapacityValue.Text += $" ADVARSEL: Kun {availableDataColumns} kolonner tilbage til data!";
                lblCapacityValue.ForeColor = Color.DarkRed;
            }
            else if (availableDataColumns < 300)
            {
                lblCapacityValue.Text += $" BEMÆRK: {availableDataColumns} kolonner tilbage - mange splits.";
                lblCapacityValue.ForeColor = Color.Orange;
            }
        }

        /// <summary>
        /// Validér om den aktuelle PK konfiguration er gyldig
        /// </summary>
        public bool IsValid()
        {
            return _primaryKeyInfo.IsValid();
        }

        /// <summary>
        /// Hent fejlmeddelelse hvis konfiguration er ugyldig
        /// </summary>
        public string GetValidationError()
        {
            if (!_primaryKeyInfo.IsValid())
                return "Mindst én primærnøgle skal vælges (eksisterende kolonne eller auto-genereret).";

            return "";
        }
    }
}